### ISSUE TITLE
Use `authplain` instead of `authldap`

### ISSUE THREAD

**Issue by sgiraudot** [YunoHost-Apps/dokuwiki_ynh#29]
I'm posting this here as it seems specific to the way DokuWiki is set up with YunoHost.

Is there a way to use the plain authentication instead of the LDAP one? When I try to put `authplain` in the configuration, of course there is no plain user and I can't connect anymore (so I can't add users). Plus I have this error on the login page:

> No ACL setup yet! Denying access to everyone.

The few answers I found about this error on forums and websites are not helping.

Thanks in advance ;)

**Comment by magikcypress** [comment]
Hello,

I use this parameters in my conf/dokuwiki.php file.

> $conf['authtype']    = 'authplain';      //which authentication backend should be used
> $conf['passcrypt']   = 'smd5';           //Used crypt method (smd5,md5,sha1,ssha,crypt,mysql,my411)
> $conf['defaultgroup']= 'user';           //Default groups new Users are added to

And add a user parameter into conf/users.auth.php

> users:password:full_user:user@example.tld:admin,user

More informations: https://www.dokuwiki.org/faq:forgotten_password
