### ISSUE TITLE
Update script doesn't update nginx configuration file

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/dokuwiki_ynh#31]
When upgrading this package, the script doesn't handle upgrading the nginx configuration file, although some enhancements can be applied by upgrading (like [this one](https://github.com/YunoHost-Apps/dokuwiki_ynh/commit/5930dc76ecf761e9734e3a838ed7ffbe4087fd0e))

**Comment by Gofannon** [comment]
Should be fixed by the new version I guess ? https://github.com/YunoHost-Apps/dokuwiki_ynh/blob/testing/scripts/upgrade#L178-L183
