### ISSUE TITLE
Update for new versions

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/dokuwiki_ynh#32]
Hello dear maintainer(s),

My wiki install screams that there are updates (49.3-4-5), refering to http://download.dokuwiki.org/ . 
`Hotfix release available: 2017-02-19e "Frusterick Manners". upgrade now! [49.5] (what's this?)`

Do you have any time to publish an update to this package ?

Thanks a lot !

**Comment by Jaxom99** [comment]
I tried via the "upgrade plugin" : some file permissions prevents me from doing so. I chown-ed the whole directory to dokuwiki:dokuwiki but the upgrade didn't complete.

And then I tried via the official way, which is to overwrite files with the new version : login was disabled, admin section disappeared, and anyone could edit the wiki. Hopefully I was able to reverse the overwritting from a previous backup.

My waiting solution to the warnings is : edit doku.php and change $update_version to the current number (50.1). It will hide the warnings...

**Comment by Gofannon** [comment]
If you can, could you try the testing version of Dokuwiki and give feedback ?

See here for details and instructions : https://forum.yunohost.org/t/official-app-dokuwiki/5366

**Comment by Jaxom99** [comment]
So here is the steps I followed : 
- Install of the regular app on a different subdomain
  - No alert for update is shown on the website, although version is still "Frustering". (?!)
- Adding the "upgrade" plugin via admin panel
  - says there is an upgrade (from Frustering to Greebo) but fails to do it (files not writable, same error as before)
- switching to testing version via CLI `sudo yunohost app upgrade dokuwiki__2 -u https://github.com/YunoHost-Apps/dokuwiki_ynh/tree/testing --debug`
  - the last version (2018-*) is fetched from the dokuwiki website
- the dokuwiki is then on "Greebo" version 👍 and the upgrade plugin says there's no upgrade.

➡️ All in all, the yunohost "testing" version works. However I don't get why I don't have the warnings on this install (whereas on the first dokuwiki app, if I remove my workaround, the warnings are displayed).

I hope it enlightens you in some way !
_NB : I forgot to mention it before, I run raspbian jessie on a Pi3, and Ynh is v2.7.14_

**Comment by Gofannon** [comment]
Thanks for the feedback. Glad to know it worked for you espacially on raspberry as I did not test on it.
I will report it on the forum so other people will get the feedback.

> arrow_right All in all, the yunohost "testing" version works. However I don't get why I don't have the warnings on this install (whereas on the first dokuwiki app, if I remove my workaround, the warnings are displayed).

According to the page https://www.dokuwiki.org/update_check, updates are checked only once a day so I guess that you should wait one day to get the warning

**Comment by Jaxom99** [comment]
OK, thanks for clarifying that. I stay available for any further inspection before the app' change !

**Comment by Gofannon** [comment]
Hello,

A new `stable version` has been released following the `testing version` you already tried. There have been other fixes in the meantime.

Feel free to try it

**Comment by Jaxom99** [comment]
I did try, and the upgrade went well for the first instance of DW, but now it returns a 502. Nginx logs indicate "open() "/usr/share/nginx/htmlindex.php" failed (2: No such file or directory)"

Furthermore the second instance of DW refused to upgrade, and disappeared because of upgrade errors (it's not on the tile menu anymore, and the data was removed from /var/www 😞 ) There is a backup though. Where should I report this upgrade bug ? In the log, there is a strange line with a "//" in the path : 

> 2018-11-09 11:22:05,727: WARNING - File /etc/nginx/conf.d/calc.tchack.xyz.d/dokuwiki__2.conf has been manually modified since the installation or last upgrade. So it has been duplicated in /home/yunohost.conf/backup//etc/nginx/conf.d/calc.tchack.xyz.d/dokuwiki__2.conf.backup.20181109.112205

**Comment by Gofannon** [comment]
Thanks for your feedback.

Somebody had a similar issue while upgrading the wiki (See https://github.com/YunoHost-Apps/dokuwiki_ynh/issues/43 and https://github.com/YunoHost/issues/issues/1231)

To sum up, there was a problem on the server with Nginx that made the upgrade to fail. After upgrading, Yunohost removed the new version to restore the pre-upgrade version. But there was a bug in the Dokuwiki restore script and it did not backup the data properly in the first place... So you end up with your data being purged.

About your issue, I believe that you could get more answers by posting of the Yunohost forum as on Github, you will reach fewer people : some applications maintainers and Yunohost people.

Could you post the following logs :
- full log file of the upgrade
- nginx
- php

Feel free to ask if you need help to locate theses files

**Comment by Jaxom99** [comment]
Thanks for your help :)
Here are the logs of ynh operations : 
- upgrade of DW first instance https://paste.yunohost.org/ojexiyapum
- upgrade of DW second instance https://paste.yunohost.org/ulaberezin
- app remove of DW2 https://paste.yunohost.org/ayicamezir
- backup-restore DW2 https://paste.yunohost.org/lorenomove
- remove on failed restore DW2 https://paste.yunohost.org/ubepobabis
Nginx is here : 
- Access (errors around 12:40:26 today) : https://paste.yunohost.org/fanocutiji 
- Errors  https://paste.yunohost.org/icasaxigoq
And PHP : https://paste.yunohost.org/idacasipor

Is this everything you need ?

**Comment by Gofannon** [comment]
It looks good, thanks. Had a quick look at `upgrade of DW second instance` and can confirm that the backup script has the same bug : it does not backup data. Too bad for a backup script ... 

Did not search for the reason of the upgrade failure as I cannot have a look right now. I should be able to have a look next week.

With all these logs, you could post on the forum to get an answer more quickly.

**Comment by Gofannon** [comment]
I replied on the forum https://forum.yunohost.org/t/official-app-dokuwiki/5366/10
