### ISSUE TITLE
Permission issue 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/dokuwiki_ynh#36]
Few plugins are not working because dokuwiki fails permission test. https://www.dokuwiki.org/tips:fixperms.php 

Log of output of fixperms.php is attached as an attachment.
[dokuwiki_fixperms_log.txt](https://github.com/YunoHost-Apps/dokuwiki_ynh/files/1977935/dokuwiki_fixperms_log.txt)

**Comment by Gofannon** [comment]
If you can, could you try the testing version of Dokuwiki and give feedback ?

See here for details and instructions : https://forum.yunohost.org/t/official-app-dokuwiki/5366

**Comment by Gofannon** [comment]
Hello,

As there is a new version, could you install it and try to install plugins again to see if the issue is still there? (there was a lot of changes about permissions)
