### ISSUE TITLE
Add URL rewriting for prettier URL

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/dokuwiki_ynh#51]
See
- https://forum.yunohost.org/t/official-app-dokuwiki/5366/16
- https://www.dokuwiki.org/config:userewrite
- https://www.dokuwiki.org/rewrite

**Comment by ashledombos** [comment]
https://forum.yunohost.org/t/dokuwiki-activer-la-reecriture-durl-userewrite-1/6357
