### ISSUE TITLE
SQLite & PDO SQLite support missing in this PHP install

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/dokuwiki_ynh#52]
Today I did a fresh installation aof dokuwiki and installed also the plugins davcal an webdavclient:

https://www.dokuwiki.org/plugin:davcal
https://www.dokuwiki.org/plugin:webdavclient

now I get the error: 

"SQLite & PDO SQLite support missing in this PHP install - plugin will not work"

Why? can someone help ? Thansk

**Comment by Gofannon** [comment]
Hello,

Can you describe what you did on your installation to install these modules? How and where do you get the error?

I would like to reproduce the issue on my setup.

**Comment by rocky-III** [comment]
thanks for asking...
finaly I solved the problem with help form the forum
https://forum.yunohost.org/t/dokuwiki-sqlite-pdo-sqlite-php/9542
