### ISSUE TITLE
How to find filepath for installation?

### ISSUE THREAD

**Issue by SpencerDub** [YunoHost-Apps/dokuwiki_ynh#53]
I'm trying to configure a template, [Material](https://www.dokuwiki.org/template:material). In its installation instructions, it says:

> 2. navigate to the `DOKUWIKI_ROOT/lib/tpl/material` folder
> 3. open the `style.ini` file and scroll to the “replacements” section
> ...

I know this is a really silly question, but how can I figure out the root path to DokuWiki on my server so I can find this folder and edit the `style.ini` file?

**Comment by kay0u** [comment]
Hi!

If you can read batch:
https://github.com/YunoHost-Apps/dokuwiki_ynh/blob/7de40f5a7c51b29248cdf24e408b014c9008119b/scripts/install#L36

Else, your app should be installed at `/var/www/dokuwiki` :-)

**Comment by SpencerDub** [comment]
Perfect! Thanks, @kay0u!
