### ISSUE TITLE
Give Gofannon write access to this repository

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/dokuwiki_ynh#59]
Do you mind adding me to the group https://github.com/orgs/YunoHost-Apps/teams/dokuwiki so I can push branches directly on this repo?

If this is no "official apps" anymore, who will have the responsibility of them? (apps-team and/or packagers of the app ?)

**Comment by maniackcrudelis** [comment]
Done

By "them" you means those repo ?
As it is for any other repo in this organization, the responsibility is on the maintainer (or team if there is).
Still, the apps group does have an admin access on all apps.

Regarding this app, as you did ask for the high_quality tag, the apps group will be somehow responsible as reviewer of all pull request..

**Comment by Gofannon** [comment]
> Done

Thanks

> By "them" you means those repo ?

Exactly

> As it is for any other repo in this organization, the responsibility is on the maintainer (or team if there is).
> Still, the apps group does have an admin access on all apps.

 Ok!

> Regarding this app, as you did ask for the high_quality tag, the apps group will be somehow responsible as reviewer of all pull request..

That was my understanding of HQ-apps and I agree with it.
And I see that a CI job has been triggered for the PR a made. https://ci-apps-hq.yunohost.org/jenkins/job/dokuwiki_ynh%20PR58/
Is it automated? (no need to run pcheck locally then?)

**Comment by maniackcrudelis** [comment]
>  Is it automated? (no need to run pcheck locally then?)

Yep, as long as the app has the high quality tag, all pull request will be tested on this CI.

**Comment by Gofannon** [comment]
That's a good idea!

Thanks for your explanation and time. Closing this issue
