### ISSUE TITLE
Upgrade misses plugins, leave website stuck

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/dokuwiki_ynh#72]
Hello,

First of all, thanks for your energy in bringing this package up to date :slightly_smiling_face: :tada: 

I encountered the following bug on my ynh 3.8 instance (with only 3-4 apps): after upgrading, the wiki web interface was stuck with the message "ACL not setup, denying all access", and I could not login to change settings. I checked the files and permissions via SSH but everything was normal.

:arrow_right:  It turns out that when upgrading from php7.0 to php7.3 for this app, many plugins were not installed. In particular php7.3-xml and php7.3-ldap were missing. After adding them manually via SSH, the wiki went back to fully fonctionnal.

Soo, easy fix ? :smile:

**Comment by ericgaspar** [comment]
thanks for pointing this out. #74 should solve this
